name: oc_forward_model
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9.12
  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::ipywidgets
  - conda-forge::ipympl
  - conda-forge::glob2
  - conda-forge::jupyterlab